version: "3.8"
services:
  symfony-app:
    build:
      args:
        user: www
        uid: 1000
      context: ./php
      dockerfile: Dockerfile
    container_name: symfony-app
    restart: unless-stopped
    working_dir: /var/www/app

    volumes:
      - ./app/:/var/www/app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # MacOS/windows: host.docker.internal
    # environment:
    #  XDEBUG_CLIENT_HOST: host.docker.internal
    #  XDEBUG_CLIENT_PORT: 9003
    #  PHP_IDE_CONFIG: serverName=cands-phpunit
    networks:
      - app-network

  symfony-db:
    image: mysql:5.7
    deploy:
      resources:
        limits:
          memory: 1024M
    container_name: symfony-db
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app/:/var/www/app/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${DATABASE_MONGO_URL}
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
